# Generated by Django 4.1.7 on 2023-03-16 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='th.jpg', upload_to='profile_avatars'),
        ),
    ]
